spring.application.name=api-visitor

spring.datasource.url=jdbc:mysql://${DB_ADDRESS}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=false

server.port=${SERVER_PORT}

jwt.secret=fairpilot-secret-key-must-be-at-least-32-characters-long!!
jwt.expiration-ms=86400000
oauth.google.client-id=${GOOGLE_CLIENT_ID:dummy-client-id}
toss.secret-key=${TOSS_SECRET_KEY:test_sk_dummy}

# ?? AWS S3 ????????????????????????????????????????????????
aws.access-key=${AWS_ACCESS_KEY:dummy}
aws.secret-key=${AWS_SECRET_KEY:dummy}
aws.s3.bucket=${AWS_S3_BUCKET:fairpilot-dev}
aws.s3.region=${AWS_S3_REGION:ap-northeast-2}

# ?? ?? ??? ?? ?? ???????????????????????????????????
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB